name: Build LaTeX document
on:
  push:
  pull_request:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: courses/intermediate-logic
          root_file: il-screen.tex
      - name: Upload il-screen.pdf
        uses: actions/upload-artifact@master
        with:
          name: il-screen.pdf
          path: courses/intermediate-logic/il-screen.pdf
